name: GitHub repository metadata exporter
description: GitHub action to export repository metadata to Sentinel
author: "Canadian Digital Service"

inputs:
  github-token:
    description: "GitHub Token used to query data from the GitHub API"
    required: true
  log-workspace-id:
    description: "Azure Log Workspace ID"
    required: true
  log-workspace-key:
    description: "Azure Log Workspace Key"
    required: true

runs:
  using: "node16"
  main: "dist/index.js"

branding:
  icon: "sunrise"
  color: "white"
