name: GitHub repository metadata exporter
description: GitHub action to export repository metadata to Sentinel
author: "Canadian Digital Service"

inputs:
  s3-bucket:
    description: "S3 bucket to upload data to"
    required: true
  aws-region:
    description: "AWS region for S3 uploads"
    required: true
  github-app-id:
    description: "GitHub App ID to call the GitHub API"
    required: true
  github-app-installation-id:
    description: "GitHub App Installation ID to call the GitHub API"
    required: true
  github-app-private-key:
    description: "GitHub App private key to call the GitHub API"
    required: true
  log-analytics-workspace-id:
    description: "Azure Log Analytics Workspace ID"
    required: true
  log-analytics-workspace-key:
    description: "Azure Log Analytics Workspace Key"
    required: true
  org-data-repo:
    description: "{owner}/{repo} that collects org data"
    required: false

runs:
  using: "node16"
  main: "dist/index.js"

branding:
  icon: "sunrise"
  color: "white"
