name: GitHub repository metadata exporter
on:
  workflow_dispatch:
  schedule:
    - cron: "0 7 * * *"

jobs:
  export-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f095bcc56b7c2baf48f3ac70d6d6782f4f553222
      - name: Export Data
        uses: ./
        with:
          github-app-id: ${{ secrets.SRE_BOT_RO_APP_ID }}
          github-app-installation-id: ${{ secrets.SRE_BOT_RO_INSTALLATION_ID }}
          github-app-private-key: ${{ secrets.SRE_BOT_RO_PRIVATE_KEY }}
          log-analytics-workspace-id: ${{ secrets.LOG_ANALYTICS_WORKSPACE_ID }}
          log-analytics-workspace-key: ${{ secrets.LOG_ANALYTICS_WORKSPACE_KEY }}
          org-data-repo: "cds-snc/github-repository-metadata-exporter" # This should only be set to true in one repo
