name: Test GitHub repository metadata exporter
on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
      - name: Test
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          log-workspace-id: ${{ secrets.LOG_WORKSPACE_ID }}
          log-workspace-key: ${{ secrets.LOG_WORKSPACE_KEY }}
