name: GitHub repository metadata exporter
on:
  workflow_dispatch:
  schedule:
    - cron: "0 7 * * *"

jobs:
  export-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
      - name: Export Data
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          log-analytics-workspace-id: ${{ secrets.LOG_ANALYTICS_WORKSPACE_ID }}
          log-analytics-workspace-key: ${{ secrets.LOG_ANALYTICS_WORKSPACE_KEY }}
